package com.proxym;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class FeignTest {
    @Autowired
    Auth0ManagementFeignClient auth0ManagementFeignClient;

    @RequestMapping(value = "/verify/test")
    public String loginUser() {
        String ch = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJqQXhSa1UyUVRSQlFqazNOMEpCTVVNM09ERTNNamRFTXpnek4wWkVPVFkxUkVJMFJrVXlSQSJ9.eyJpc3MiOiJodHRwczovL2Rldi1heTl3aTZoei5hdXRoMC5jb20vIiwic3ViIjoiU1ZYOU42cUR2ZXE2cUJoMDVqY3FJeXFZaFN0YTJFd3ZAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vZGV2LWF5OXdpNmh6LmF1dGgwLmNvbS9hcGkvdjIvIiwiaWF0IjoxNTYyMzI0MTMxLCJleHAiOjE1NjI0MTA1MzEsImF6cCI6IlNWWDlONnFEdmVxNnFCaDA1amNxSXlxWWhTdGEyRXd2Iiwic2NvcGUiOiJyZWFkOnVzZXJzIHVwZGF0ZTp1c2VycyBkZWxldGU6dXNlcnMgY3JlYXRlOnVzZXJzIHJlYWQ6dXNlcnNfYXBwX21ldGFkYXRhIHVwZGF0ZTp1c2Vyc19hcHBfbWV0YWRhdGEgZGVsZXRlOnVzZXJzX2FwcF9tZXRhZGF0YSBjcmVhdGU6dXNlcnNfYXBwX21ldGFkYXRhIHJlYWQ6dXNlcl9pZHBfdG9rZW5zIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.OkJOwYAKJp21Y_yDKc9DsGel042blWLHC2MYGfBxDve5G7QGCKG_5w9_TzL_7iPhmchoGFVuG6tS2_-YfXFMCpFONrFmVOzV3j-M-mEr-_e8ccaKwr0CAPg46cylqpPI0sTGpIUeSXAPxVmSYiteNquVCU4vuHpyEWISKfpPFW0JQYTvj6Uepyao-60ZLZTiGbkve1TWhkr-Rc2qitP-s5m1CCBD_yEMyFahkaLNd4C-eRSeiwlb1k2r-XkwNjz8ojiL6MP_f2wbdGYfHy5g6jA0KlPEwLuWAhUg1ZHkptLJWU7csW3kyaLuRqtW45NjRpE0iJbP4tdfSTcaxxod5Q";
        return auth0ManagementFeignClient.verifySignatureFeign(ch);
    }
}
